#!/usr/bin/env python3
"""Convert a simple text XYZ point file to an ASCII PLY vertex file.

Each non-empty, non-comment input line must contain at least three numeric
columns. Extra columns are ignored. Delimiters can be whitespace or a declared
single-character delimiter such as a comma.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="input XYZ/text file")
    parser.add_argument("output", type=Path, help="output ASCII PLY file")
    parser.add_argument(
        "--delimiter",
        default=None,
        help="field delimiter; default is arbitrary whitespace (use ',' for CSV)",
    )
    parser.add_argument(
        "--skip-lines",
        type=int,
        default=0,
        help="number of leading physical lines to skip",
    )
    return parser.parse_args()


def load_points(path: Path, delimiter: str | None, skip_lines: int) -> list[tuple[float, float, float]]:
    if skip_lines < 0:
        raise ValueError("--skip-lines must be non-negative")
    points: list[tuple[float, float, float]] = []
    with path.open("r", encoding="utf-8-sig") as stream:
        for line_number, raw in enumerate(stream, start=1):
            if line_number <= skip_lines:
                continue
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            fields = line.split(delimiter) if delimiter is not None else line.split()
            if len(fields) < 3:
                raise ValueError(f"{path}:{line_number}: expected at least three columns")
            try:
                point = tuple(float(fields[i].strip()) for i in range(3))
            except ValueError as error:
                raise ValueError(f"{path}:{line_number}: invalid x/y/z value") from error
            if not all(math.isfinite(value) for value in point):
                raise ValueError(f"{path}:{line_number}: x/y/z must be finite")
            points.append((point[0], point[1], point[2]))
    if not points:
        raise ValueError(f"{path}: no points found")
    return points


def write_ply(path: Path, points: list[tuple[float, float, float]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="ascii", newline="\n") as stream:
        stream.write("ply\n")
        stream.write("format ascii 1.0\n")
        stream.write("comment generated by tools/xyz_to_ply.py\n")
        stream.write(f"element vertex {len(points)}\n")
        stream.write("property float x\nproperty float y\nproperty float z\n")
        stream.write("end_header\n")
        for x, y, z in points:
            stream.write(f"{x:.9g} {y:.9g} {z:.9g}\n")


def main() -> int:
    args = parse_args()
    delimiter = args.delimiter
    if delimiter == r"\t":
        delimiter = "\t"
    if delimiter is not None and len(delimiter) != 1:
        raise ValueError("--delimiter must be one character or \\t")
    points = load_points(args.input, delimiter, args.skip_lines)
    write_ply(args.output, points)
    print(f"Wrote {len(points)} vertices to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
